### ISSUE TITLE
Rails 7 Version

### ISSUE THREAD

**Issue by johnnyb** [mathieujobin/activerecord-mysql-uuid-column#8]
Is there any possibility of a Rails 7 version of this?

**Comment by mathieujobin** [comment]
yes, that's possible... I wasn't aware anyone was using it ...

**Comment by mathieujobin** [comment]
Can you try out the `rails7` branch I just pushed?

Feel free to also review the PR

https://github.com/mathieujobin/activerecord-mysql-uuid-column/pull/9
